# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='owner_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
