# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCloud', '0002_auto_20161002_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='File_storage',
        ),
    ]
