# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCloud', '0003_auto_20161002_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_storage',
            new_name='Storage',
        ),
    ]
