# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCloud', '0006_auto_20161002_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='Files',
        ),
    ]
