# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCloud', '0007_auto_20161002_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='owner_name',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
