# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
