# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public_Cloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='files',
            name='user_name',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
