# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public_Cloud', '0002_auto_20161008_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='user_name',
            new_name='owner_name',
        ),
    ]
